name: AutoBuildAndTransCheck

on: 
  pull_request:
    types: [opened, edited]

jobs:
  build_check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v1
      - name: RestoreNugetPackage
        run: nuget restore ExtremeRoles.sln
      - name: SetupPython
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: InstallPythonLibrary
        run: pip install openpyxl
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.9
        with:
          sdk-version: 18362
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: CheckTransData
        continue-on-error: true
        run: python createTransReport.py
      - name: RunBuild
        id: build
        continue-on-error: true
        run: msbuild ExtremeRoles.sln -p:Configuration=Release
      - name: PostComment
        uses: NejcZdovc/comment-pr@v2
        with:
          file: "comment.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BuildResult: ${{ steps.build.outcome }}